# Generated by Django 5.2.1 on 2025-05-14 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fruit",
            name="branch",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fruit_set",
                to="simulation.branch",
            ),
            preserve_default=False,
        ),
    ]
